/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package SplitPerfect

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.runApplication

@SpringBootApplication
class SplitPerfectApplication
fun main(args: Array<String>) {
    runApplication<SplitPerfectApplication>(*args)
}
