/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package SplitPerfect

import org.junit.jupiter.api.BeforeEach


class AppTest {

    @BeforeEach
    fun initialize() {
    }




}
